import { logErrorBrief } from '../../logger/compact-error';
import { getSupabaseServiceConfig } from '../shared/supabase';
import type { ChartSpec } from '../../insights/types';

/** What a token-free action button does when clicked (handled by REST/navigation, never the agent).
 *  'dismiss' is purely client-side (disable the buttons, no request). */
export type NotificationActionKind =
  | 'sync_action'
  | 'propagate'
  | 'resync'
  | 'list_on_marketplace'
  | 'link'
  | 'dismiss';

export interface NotificationAction {
  /** Choice id sent to the endpoint (e.g. 'create' | 'create_always' | 'map' | 'skip' | 'undo'). */
  id: string;
  label: string;
  kind: NotificationActionKind;
  style?: 'primary' | 'default' | 'danger';
  /** For kind 'link' / 'list_on_marketplace': where to navigate. */
  href?: string;
}

/** Identifiers an action needs to resolve its target server-side. */
export interface NotificationContextRef {
  linkId?: string;
  internalProductId?: string;
  platform?: string;
  productId?: string;
  shopId?: string;
  /** Bidirectional-sync propagation proposal (the 'propagate' action targets this). */
  proposalId?: string;
  attribute?: 'stock' | 'price';
}

/** Payload delivered to a tenant's web/native clients over Supabase Realtime. */
export interface TenantNotificationPayload {
  id: string;
  text: string;
  kind: 'marketplace' | 'connection' | 'product_sync' | 'insight';
  platform?: string;
  category?: string;
  code?: string;
  createdAt: string;
  /** Token-free interactive buttons (product-sync prompts). Absent for plain notifications. */
  actions?: NotificationAction[];
  contextRef?: NotificationContextRef;
  /** Deterministic charts rendered in the chat (scheduled business insights). */
  charts?: ChartSpec[];
  /** True when generated by deterministic templates (no LLM) — lets the client/telemetry distinguish. */
  deterministic?: boolean;
}

/** Per-tenant private Broadcast topic. Clients subscribe to `tenant:<id>` (RLS-gated). */
export function tenantTopic(tenantId: string): string {
  return `tenant:${tenantId}`;
}

/**
 * Broadcast a notification to a tenant's clients via the Supabase Realtime REST endpoint.
 * Server-side, authenticated with the service key (bypasses the RLS policy that gates which
 * clients may *receive* the topic). Best-effort: returns false (and logs) instead of throwing.
 */
export async function broadcastTenantNotification(
  tenantId: string,
  payload: TenantNotificationPayload,
): Promise<boolean> {
  const cfg = getSupabaseServiceConfig();
  if (!cfg) return false;

  try {
    const res = await fetch(`${cfg.url}/realtime/v1/api/broadcast`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: cfg.key,
        Authorization: `Bearer ${cfg.key}`,
      },
      body: JSON.stringify({
        messages: [
          { topic: tenantTopic(tenantId), event: 'notification', private: true, payload },
        ],
      }),
    });
    if (!res.ok) {
      logErrorBrief(`[realtime] broadcast failed (${res.status}) tenant=${tenantId}`, await safeText(res));
      return false;
    }
    return true;
  } catch (err) {
    logErrorBrief(`[realtime] broadcast threw tenant=${tenantId}`, err);
    return false;
  }
}

async function safeText(res: Response): Promise<string> {
  try {
    return await res.text();
  } catch {
    return '';
  }
}
