// Renders a research report as a standalone HTML email — same content as the web report page, but
// self-contained (no JS charts; email clients can't run Recharts) so it reads fine in any inbox.
import { webAppAbsoluteUrl } from '../../server/web-app-origin';
import type { ResearchReportContent } from './reports-repo';

export interface ReportEmail {
  subject: string;
  html: string;
  text: string;
}

export function buildReportEmail(args: { reportId: string; topic: string; content: ResearchReportContent }): ReportEmail {
  const { reportId, topic, content } = args;
  const reportUrl = webAppAbsoluteUrl(`/reports/${reportId}`);

  const sectionsHtml = content.sections
    .map((s) => `<h2 style="${H2_STYLE}">${escHtml(s.heading)}</h2>${renderBodyHtml(s.body)}`)
    .join('\n');

  const chartsHtml = content.charts.length > 0 ? content.charts.map(renderChartHtml).join('\n') : '';

  const imagesHtml =
    content.images.length > 0
      ? content.images
          .map(
            (img) =>
              `<div style="margin:16px 0"><img src="${escHtml(img.url)}" alt="${escHtml(img.caption ?? '')}" style="max-width:100%;border-radius:8px;border:1px solid #e5e5e5" />${
                img.caption ? `<p style="${CAPTION_STYLE}">${escHtml(img.caption)}</p>` : ''
              }</div>`,
          )
          .join('\n')
      : '';

  const citationsHtml =
    content.citations.length > 0
      ? `<h2 style="${H2_STYLE}">Sources</h2><ul style="padding-left:20px;margin:0 0 16px">${content.citations
          .map(
            (c) =>
              `<li style="margin-bottom:8px"><a href="${escHtml(c.url)}" style="color:#dc4a1e;text-decoration:underline">${escHtml(c.title)}</a>${
                c.excerpt ? `<div style="${CAPTION_STYLE}">${escHtml(c.excerpt)}</div>` : ''
              }</li>`,
          )
          .join('\n')}</ul>`
      : '';

  const html = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escHtml(topic)}</title></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,'Segoe UI',Roboto,sans-serif;color:#111">
<div style="max-width:600px;margin:0 auto;padding:32px 20px">
  <div style="display:flex;align-items:center;gap:8px;margin-bottom:32px">
    <div style="width:24px;height:24px;background:#dc4a1e;border-radius:6px"></div>
    <span style="font-size:14px;font-weight:600">Lntera</span>
  </div>
  <p style="font-size:11px;font-weight:500;letter-spacing:.08em;text-transform:uppercase;color:#999;margin:0 0 8px">Research report</p>
  <h1 style="font-size:24px;font-weight:600;letter-spacing:-.02em;margin:0 0 24px;line-height:1.2">${escHtml(topic)}</h1>
  ${sectionsHtml}
  ${chartsHtml}
  ${imagesHtml}
  ${citationsHtml}
  <div style="margin-top:32px">
    <a href="${escHtml(reportUrl)}" style="display:inline-block;background:#dc4a1e;color:#fff;text-decoration:none;padding:11px 20px;border-radius:8px;font-size:14px;font-weight:500">View full report &amp; ask follow-ups &rarr;</a>
  </div>
  <p style="font-size:12px;color:#999;margin-top:32px">This report was generated by your Lntera Active Agent.</p>
</div>
</body>
</html>`;

  const text = [
    `${topic}\n`,
    ...content.sections.map((s) => `${s.heading}\n${stripMarkdownLite(s.body)}\n`),
    content.citations.length > 0
      ? `Sources:\n${content.citations.map((c) => `- ${c.title}: ${c.url}`).join('\n')}\n`
      : '',
    `View the full report: ${reportUrl}`,
  ]
    .filter(Boolean)
    .join('\n');

  return { subject: `Your research report: ${topic}`, html, text };
}

const H2_STYLE = 'font-size:16px;font-weight:600;margin:24px 0 8px;letter-spacing:-.01em';
const CAPTION_STYLE = 'font-size:12px;color:#777;margin:4px 0 0';

/** Charts render as a plain HTML table — email clients can't run Recharts/JS. A 'forecast' chart notes
 *  where the projection begins rather than trying to visually distinguish it in a table. */
function renderChartHtml(chart: ResearchReportContent['charts'][number]): string {
  const rows = chart.labels
    .map((label, i) => {
      const cells = chart.series.map((s) => `<td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">${s.data[i] ?? ''}</td>`).join('');
      return `<tr><td style="padding:6px 10px;border-bottom:1px solid #eee;color:#666">${escHtml(label)}</td>${cells}</tr>`;
    })
    .join('\n');
  const header = chart.series
    .map((s, i) => `<th style="padding:6px 10px;border-bottom:2px solid #ddd;text-align:right;font-size:12px;color:#666">${escHtml(s.name ?? `Series ${i + 1}`)}${chart.unit ? ` (${escHtml(chart.unit)})` : ''}</th>`)
    .join('');
  const note =
    chart.type === 'forecast' && typeof chart.forecastFromIndex === 'number' && chart.labels[chart.forecastFromIndex]
      ? `<p style="${CAPTION_STYLE}">Projected from ${escHtml(chart.labels[chart.forecastFromIndex])} onward — treat as an estimate, not a guarantee.</p>`
      : '';
  return `<h3 style="font-size:14px;font-weight:600;margin:16px 0 8px">${escHtml(chart.title)}</h3>
<table style="width:100%;border-collapse:collapse;margin-bottom:4px"><thead><tr><th style="padding:6px 10px;border-bottom:2px solid #ddd"></th>${header}</tr></thead><tbody>${rows}</tbody></table>
${note}`;
}

/** Minimal markdown → HTML: paragraphs, **bold**, and "- "/"* " bullet lists. Good enough for the
 *  agent's own report prose (short paragraphs + occasional bullets) without pulling in a markdown lib
 *  server-side just for this one email template. */
function renderBodyHtml(markdown: string): string {
  const blocks = markdown.trim().split(/\n\s*\n/);
  return blocks
    .map((block) => {
      const lines = block.split('\n').map((l) => l.trim()).filter(Boolean);
      if (lines.length > 0 && lines.every((l) => /^[-*]\s+/.test(l))) {
        const items = lines.map((l) => `<li style="margin-bottom:4px">${inlineMarkdown(l.replace(/^[-*]\s+/, ''))}</li>`).join('');
        return `<ul style="padding-left:20px;margin:0 0 12px">${items}</ul>`;
      }
      return `<p style="font-size:14px;line-height:1.6;margin:0 0 12px;color:#222">${inlineMarkdown(lines.join(' '))}</p>`;
    })
    .join('\n');
}

function inlineMarkdown(text: string): string {
  return escHtml(text).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
}

/** Plain-text fallback: strip markdown emphasis/bullet markers, keep the words. */
function stripMarkdownLite(markdown: string): string {
  return markdown
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/^[-*]\s+/gm, '• ')
    .trim();
}

function escHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
